version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    reviewers:
      - bitpatty
    labels:
      - dependencies
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'
