trigger:
  branches:
    include:
      - master

pr: none

pool:
  vmImage: "windows-latest"

steps:
  - task: PowerShell@2
    displayName: "Update archives"
    inputs:
      targetType: "filePath"
      filePath: "./update_archives.azure.ps1"
      failOnStderr: true
      workingDirectory: $(Build.SourcesDirectory)
  - task: NodeTool@0
    displayName: "Setup node 12.x"
    inputs:
      versionSpec: "12.x"
  - task: PowerShell@2
    displayName: "Create Build"
    inputs:
      targetType: "filePath"
      filePath: "./build.azure.ps1"
      failOnStderr: true
      workingDirectory: $(Build.SourcesDirectory)
  - task: PowerShell@2
    displayName: "Push Changes"
    condition: succeeded()
    env:
      GitHub_PAT: $(GitHub_PAT)
    inputs:
      targetType: "inline"
      script: "git push -uqf $(GitHub_PAT) HEAD:gh-pages;"
      failOnStderr: true
      workingDirectory: $(Build.SourcesDirectory)/docs/.vuepress/dist
