version: '3.7'

services:
  gct_generator:
    container_name: gct_generator
    build:
      context: ./
      dockerfile: ./dockerfiles/Serve.Dockerfile
    network_mode: 'bridge'
    ports:
      - '8080:80'
