name: Code/Feature Request
description: Suggest an idea for a code or generator feature
title: '[FEAT]'
labels:
  - enhancement
assignees:
  - 'BitPatty'
body:
  - type: textarea
    attributes:
      label: Is your request related to a problem? Please describe
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe the solution you'd like"
      description: 'A clear and concise description of what you want to happen.'
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: "A clear and concise description of any alternative solutions or features you've considered."
  - type: textarea
    attributes:
      label: Additional context
