name: Build

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create a new build
        run: docker build -t publisher:latest -f ./dockerfiles/Deploy.Dockerfile .
