name: Build & Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create a new build
        run: docker build -t publisher:latest -f ./dockerfiles/Deploy.Dockerfile .
      - name: Deploy to gh-pages branch
        env:
          REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
          PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
          PUBLISHER_EMAIL: ${{ secrets.PUBLISHER_EMAIL }}
        run: |
          docker run \
            --rm \
            -e REPOSITORY_TOKEN="$env:REPOSITORY_TOKEN" \
            -e PUBLISHER_NAME="$env:PUBLISHER_NAME" \
            -e PUBLISHER_EMAIL="$env:PUBLISHER_EMAIL" \
            publisher:latest
